CREATE TABLE IF NOT EXISTS PERSON (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR NOT NULL,
	LASTNAME VARCHAR NOT NULL,
	AGE VARCHAR,
	COUNTRY VARCHAR
);

CREATE TABLE IF NOT EXISTS NON_IMMIGRANT_VISA_CATEGORIES (
	CATEGORY_ID VARCHAR PRIMARY KEY,
	PURPOSE VARCHAR NOT NULL,
	DURATION INT
);

CREATE TYPE VISA_CATEGORIES_STATUS AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');

CREATE TABLE IF NOT EXISTS PERSON_NONIMMIGRANT_VISA_CATEGORIES (
	PERSON_ID SERIAL,
	CATEGORY_ID VARCHAR NOT NULL,
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	STATUS VISA_CATEGORIES_STATUS NOT NULL,

	PRIMARY KEY (PERSON_ID, CATEGORY_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID) ON UPDATE CASCADE,
  	FOREIGN KEY (CATEGORY_ID) REFERENCES NON_IMMIGRANT_VISA_CATEGORIES(CATEGORY_ID) ON UPDATE CASCADE
);

--INSERT INTO PERSON (ID,NAME,LASTNAME) VALUES ('1','Bob','Breiton');
--INSERT INTO PERSON (ID,NAME,LASTNAME,AGE,COUNTRY) VALUES ('2','Fred','Rodi','20','Monako');
--INSERT INTO PERSON (ID,NAME,LASTNAME,AGE) VALUES ('3','Kim','Vemon','18');
--INSERT INTO PERSON (ID,NAME,LASTNAME) VALUES ('4','Jailly','Reidon');
--INSERT INTO PERSON (ID,NAME,LASTNAME) VALUES ('5','Tom','Hardy');
--
--
--INSERT INTO NON_IMMIGRANT_VISA_CATEGORIES (CATEGORY_ID,PURPOSE) VALUES ('A','Diplomat or foreign government official');
--INSERT INTO NON_IMMIGRANT_VISA_CATEGORIES (CATEGORY_ID,PURPOSE,DURATION) VALUES ('H-1B','Specialty occupations in fields requiring highly specialized knowledge',180);
--INSERT INTO NON_IMMIGRANT_VISA_CATEGORIES (CATEGORY_ID,PURPOSE,DURATION) VALUES ('B-2','Tourism, vacation, pleasure visitor',180);
--INSERT INTO NON_IMMIGRANT_VISA_CATEGORIES (CATEGORY_ID,PURPOSE,DURATION) VALUES ('H-2B','Temporary worker performing other services or labor of a temporary or seasonal nature.',180);
--INSERT INTO NON_IMMIGRANT_VISA_CATEGORIES (CATEGORY_ID,PURPOSE) VALUES ('E','Treaty trader/treaty investor');
--
--
--INSERT INTO PERSON_NONIMMIGRANT_VISA_CATEGORIES (PERSON_ID,CATEGORY_ID,START_DATE,END_DATE,STATUS) VALUES (1::INTEGER,'B-2',NOW(),NOW(),'ACTIVE');
